class Vocabulary:
    def __init__(self):
        self._VN_DICT=set(line.strip() for line in open('VnVocab.txt','r',encoding='utf8'))
        self._COUNTRY_L_NAME = {"na uy"}
        self._COUNTRY_L_NAME.add("san marino")
        self._COUNTRY_L_NAME.add("phần lan")
        self._COUNTRY_L_NAME.add("bồ đào nha")
        self._COUNTRY_L_NAME.add("ca-ri-bê hà lan")
        self._COUNTRY_L_NAME.add("quần đảo bắc mariana")
        self._COUNTRY_L_NAME.add("ả rập xê-út")
        self._COUNTRY_L_NAME.add("tây ban nha")
        self._COUNTRY_L_NAME.add("quần đảo virgin")
        self._COUNTRY_L_NAME.add("đảo somoa thuộc mỹ")
        self._COUNTRY_L_NAME.add("đông timor")
        self._COUNTRY_L_NAME.add("hoa kỳ")
        self._COUNTRY_L_NAME.add("quần đảo pitcairn")
        self._COUNTRY_L_NAME.add("samoa thuộc mỹ")
        self._COUNTRY_L_NAME.add("hàn quốc")
        self._COUNTRY_L_NAME.add("đảo ascension")
        self._COUNTRY_L_NAME.add("thuỵ sĩ")
        self._COUNTRY_L_NAME.add("ai cập")
        self._COUNTRY_L_NAME.add("burkina faso")
        self._COUNTRY_L_NAME.add("mông cổ")
        self._COUNTRY_L_NAME.add("polynesia thuộc pháp")
        self._COUNTRY_L_NAME.add("turks và caicos")
        self._COUNTRY_L_NAME.add("thổ nhĩ kỳ")
        self._COUNTRY_L_NAME.add("liên bang micronesia")
        self._COUNTRY_L_NAME.add("đảo man")
        self._COUNTRY_L_NAME.add("saint helena")
        self._COUNTRY_L_NAME.add("ả rập saudi")
        self._COUNTRY_L_NAME.add("ba lan")
        self._COUNTRY_L_NAME.add("são tomé và príncipe")
        self._COUNTRY_L_NAME.add("đảo norfolk")
        self._COUNTRY_L_NAME.add("chdcnd triều tiên")
        self._COUNTRY_L_NAME.add("quần đảo canary")
        self._COUNTRY_L_NAME.add("guiana thuộc pháp")
        self._COUNTRY_L_NAME.add("antigua và barbuda")
        self._COUNTRY_L_NAME.add("saint pierre và miquelon")
        self._COUNTRY_L_NAME.add("sri lanka")
        self._COUNTRY_L_NAME.add("ceuta và melilla")
        self._COUNTRY_L_NAME.add("việt nam")
        self._COUNTRY_L_NAME.add("bờ biển ngà")
        self._COUNTRY_L_NAME.add("thuỵ điển")
        self._COUNTRY_L_NAME.add("el salvador")
        self._COUNTRY_L_NAME.add("svalbard và jan mayen")
        self._COUNTRY_L_NAME.add("saint lucia")
        self._COUNTRY_L_NAME.add("diego garcia")
        self._COUNTRY_L_NAME.add("ấn độ")
        self._COUNTRY_L_NAME.add("tây sahara")
        self._COUNTRY_L_NAME.add("quần đảo cook")
        self._COUNTRY_L_NAME.add("guinea xích đạo")
        self._COUNTRY_L_NAME.add("trung quốc")
        self._COUNTRY_L_NAME.add("chdc congo")
        self._COUNTRY_L_NAME.add("cộng hoà dominica")
        self._COUNTRY_L_NAME.add("cape verde")
        self._COUNTRY_L_NAME.add("hà lan")
        self._COUNTRY_L_NAME.add("puerto rico")
        self._COUNTRY_L_NAME.add("đài loan")
        self._COUNTRY_L_NAME.add("cộng hoà séc")
        self._COUNTRY_L_NAME.add("costa rica")
        self._COUNTRY_L_NAME.add("saint kitts và nevis")
        self._COUNTRY_L_NAME.add("nhật bản")
        self._COUNTRY_L_NAME.add("quần đảo faroe")
        self._COUNTRY_L_NAME.add("đan mạch")
        self._COUNTRY_L_NAME.add("turk và caicos")
        self._COUNTRY_L_NAME.add("cabo verde")
        self._COUNTRY_L_NAME.add("nam sudan")
        self._COUNTRY_L_NAME.add("cộng hoà trung phi")
        self._COUNTRY_L_NAME.add("trung phi")
        self._COUNTRY_L_NAME.add("saint vincent và grenadines")
        self._COUNTRY_L_NAME.add("quần đảo cocos")
        self._COUNTRY_L_NAME.add("thành vatican")
        self._COUNTRY_L_NAME.add("saint barthélemy")
        self._COUNTRY_L_NAME.add("nam cực")
        self._COUNTRY_L_NAME.add("trinidad và tobago")
        self._COUNTRY_L_NAME.add("cộng hoà congo")
        self._COUNTRY_L_NAME.add("quần đảo cayman")
        self._COUNTRY_L_NAME.add("saint martin")
        self._COUNTRY_L_NAME.add("tristan da cunha")
        self._COUNTRY_L_NAME.add("bosnia và herzegovina")
        self._COUNTRY_L_NAME.add("thái lan")
        self._COUNTRY_L_NAME.add("new zealand")
        self._COUNTRY_L_NAME.add("hồng kông")
        self._COUNTRY_L_NAME.add("wallis và futuna")
        self._COUNTRY_L_NAME.add("sierra leone")
        self._COUNTRY_L_NAME.add("sint maarten")
        self._COUNTRY_L_NAME.add("quần đảo solomon")
        self._COUNTRY_L_NAME.add("nam phi")
        self._COUNTRY_L_NAME.add("bosna và hercegovina")
        self._COUNTRY_L_NAME.add("vương quốc anh")
        self._COUNTRY_L_NAME.add("papua new guinea")
        self._COUNTRY_L_NAME.add("hy lạp")
        self._COUNTRY_L_NAME.add("đảo giáng sinh")
        self._COUNTRY_L_NAME.add("triều tiên")
        self._COUNTRY_L_NAME.add("quần đảo falkland")
        self._COUNTRY_L_NAME.add("miến điện")
        self._COUNTRY_L_NAME.add("quần đảo marshall")
        self._COUNTRY_L_NAME.add("new caledonia")
        self._COUNTRY_S_NAME={"mỹ"}
        self._COUNTRY_S_NAME.add("belarus")
        self._COUNTRY_S_NAME.add("guinée")
        self._COUNTRY_S_NAME.add("gambia")
        self._COUNTRY_S_NAME.add("cô-oét")
        self._COUNTRY_S_NAME.add("guinea")
        self._COUNTRY_S_NAME.add("estonia")
        self._COUNTRY_S_NAME.add("philippines")
        self._COUNTRY_S_NAME.add("cuba")
        self._COUNTRY_S_NAME.add("mauritius")
        self._COUNTRY_S_NAME.add("mali")
        self._COUNTRY_S_NAME.add("armenia")
        self._COUNTRY_S_NAME.add("aruba")
        self._COUNTRY_S_NAME.add("méxico")
        self._COUNTRY_S_NAME.add("ukraina")
        self._COUNTRY_S_NAME.add("bénin")
        self._COUNTRY_S_NAME.add("congo")
        self._COUNTRY_S_NAME.add("monaco")
        self._COUNTRY_S_NAME.add("séc")
        self._COUNTRY_S_NAME.add("kenya")
        self._COUNTRY_S_NAME.add("hungary")
        self._COUNTRY_S_NAME.add("greenland")
        self._COUNTRY_S_NAME.add("li-băng")
        self._COUNTRY_S_NAME.add("paraguay")
        self._COUNTRY_S_NAME.add("palau")
        self._COUNTRY_S_NAME.add("vanuatu")
        self._COUNTRY_S_NAME.add("colombia")
        self._COUNTRY_S_NAME.add("azerbaijan")
        self._COUNTRY_S_NAME.add("syria")
        self._COUNTRY_S_NAME.add("rwanda")
        self._COUNTRY_S_NAME.add("libya")
        self._COUNTRY_S_NAME.add("guernsey")
        self._COUNTRY_S_NAME.add("afghanistan")
        self._COUNTRY_S_NAME.add("guiné-bissau")
        self._COUNTRY_S_NAME.add("hungari")
        self._COUNTRY_S_NAME.add("kiribati")
        self._COUNTRY_S_NAME.add("dominica")
        self._COUNTRY_S_NAME.add("bulgaria")
        self._COUNTRY_S_NAME.add("brasil")
        self._COUNTRY_S_NAME.add("bahrain")
        self._COUNTRY_S_NAME.add("guatemala")
        self._COUNTRY_S_NAME.add("ghana")
        self._COUNTRY_S_NAME.add("somalia")
        self._COUNTRY_S_NAME.add("jamaica")
        self._COUNTRY_S_NAME.add("togo")
        self._COUNTRY_S_NAME.add("liechtenstein")
        self._COUNTRY_S_NAME.add("serbia")
        self._COUNTRY_S_NAME.add("ma-rốc")
        self._COUNTRY_S_NAME.add("bỉ")
        self._COUNTRY_S_NAME.add("úc")
        self._COUNTRY_S_NAME.add("senegal")
        self._COUNTRY_S_NAME.add("montserrat")
        self._COUNTRY_S_NAME.add("zambia")
        self._COUNTRY_S_NAME.add("namibia")
        self._COUNTRY_S_NAME.add("comoros")
        self._COUNTRY_S_NAME.add("curaçao")
        self._COUNTRY_S_NAME.add("palestine")
        self._COUNTRY_S_NAME.add("canada")
        self._COUNTRY_S_NAME.add("li-bi")
        self._COUNTRY_S_NAME.add("honduras")
        self._COUNTRY_S_NAME.add("réunion")
        self._COUNTRY_S_NAME.add("maldives")
        self._COUNTRY_S_NAME.add("chile")
        self._COUNTRY_S_NAME.add("algérie")
        self._COUNTRY_S_NAME.add("oman")
        self._COUNTRY_S_NAME.add("timor-leste")
        self._COUNTRY_S_NAME.add("brazil")
        self._COUNTRY_S_NAME.add("lesotho")
        self._COUNTRY_S_NAME.add("guyana")
        self._COUNTRY_S_NAME.add("peru")
        self._COUNTRY_S_NAME.add("malaysia")
        self._COUNTRY_S_NAME.add("jersey")
        self._COUNTRY_S_NAME.add("síp")
        self._COUNTRY_S_NAME.add("belize")
        self._COUNTRY_S_NAME.add("nauru")
        self._COUNTRY_S_NAME.add("campuchia")
        self._COUNTRY_S_NAME.add("kuwait")
        self._COUNTRY_S_NAME.add("slovenia")
        self._COUNTRY_S_NAME.add("somali")
        self._COUNTRY_S_NAME.add("haiti")
        self._COUNTRY_S_NAME.add("zimbabwe")
        self._COUNTRY_S_NAME.add("macedonia")
        self._COUNTRY_S_NAME.add("micronesia")
        self._COUNTRY_S_NAME.add("philippin")
        self._COUNTRY_S_NAME.add("bolivia")
        self._COUNTRY_S_NAME.add("brunei")
        self._COUNTRY_S_NAME.add("israel")
        self._COUNTRY_S_NAME.add("lào")
        self._COUNTRY_S_NAME.add("bangladesh")
        self._COUNTRY_S_NAME.add("ý")
        self._COUNTRY_S_NAME.add("ireland")
        self._COUNTRY_S_NAME.add("albania")
        self._COUNTRY_S_NAME.add("botswana")
        self._COUNTRY_S_NAME.add("venezuela")
        self._COUNTRY_S_NAME.add("andorra")
        self._COUNTRY_S_NAME.add("malawi")
        self._COUNTRY_S_NAME.add("moldova")
        self._COUNTRY_S_NAME.add("madagascar")
        self._COUNTRY_S_NAME.add("turkmenistan")
        self._COUNTRY_S_NAME.add("iran")
        self._COUNTRY_S_NAME.add("iraq")
        self._COUNTRY_S_NAME.add("seychelles")
        self._COUNTRY_S_NAME.add("indonesia")
        self._COUNTRY_S_NAME.add("tchad")
        self._COUNTRY_S_NAME.add("nicaragua")
        self._COUNTRY_S_NAME.add("gibraltar")
        self._COUNTRY_S_NAME.add("ethiopia")
        self._COUNTRY_S_NAME.add("ecuador")
        self._COUNTRY_S_NAME.add("guinea-bissau")
        self._COUNTRY_S_NAME.add("mauritania")
        self._COUNTRY_S_NAME.add("albani")
        self._COUNTRY_S_NAME.add("algeria")
        self._COUNTRY_S_NAME.add("mozambique")
        self._COUNTRY_S_NAME.add("cameroon")
        self._COUNTRY_S_NAME.add("vatican")
        self._COUNTRY_S_NAME.add("liban")
        self._COUNTRY_S_NAME.add("panama")
        self._COUNTRY_S_NAME.add("uae")
        self._COUNTRY_S_NAME.add("luxembourg")
        self._COUNTRY_S_NAME.add("nigeria")
        self._COUNTRY_S_NAME.add("sudan")
        self._COUNTRY_S_NAME.add("benin")
        self._COUNTRY_S_NAME.add("chad")
        self._COUNTRY_S_NAME.add("liberia")
        self._COUNTRY_S_NAME.add("djibouti")
        self._COUNTRY_S_NAME.add("đức")
        self._COUNTRY_S_NAME.add("tajikistan")
        self._COUNTRY_S_NAME.add("fiji")
        self._COUNTRY_S_NAME.add("singapore")
        self._COUNTRY_S_NAME.add("mexico")
        self._COUNTRY_S_NAME.add("samoa")
        self._COUNTRY_S_NAME.add("tunisia")
        self._COUNTRY_S_NAME.add("bahamas")
        self._COUNTRY_S_NAME.add("bhutan")
        self._COUNTRY_S_NAME.add("uganda")
        self._COUNTRY_S_NAME.add("uruguay")
        self._COUNTRY_S_NAME.add("gabon")
        self._COUNTRY_S_NAME.add("bungari")
        self._COUNTRY_S_NAME.add("niger")
        self._COUNTRY_S_NAME.add("kyrgyzstan")
        self._COUNTRY_S_NAME.add("pakistan")
        self._COUNTRY_S_NAME.add("martinique")
        self._COUNTRY_S_NAME.add("macao")
        self._COUNTRY_S_NAME.add("kosovo")
        self._COUNTRY_S_NAME.add("mayotte")
        self._COUNTRY_S_NAME.add("yemen")
        self._COUNTRY_S_NAME.add("georgia")
        self._COUNTRY_S_NAME.add("pháp")
        self._COUNTRY_S_NAME.add("ai-len")
        self._COUNTRY_S_NAME.add("argentina")
        self._COUNTRY_S_NAME.add("jordan")
        self._COUNTRY_S_NAME.add("anguilla")
        self._COUNTRY_S_NAME.add("swaziland")
        self._COUNTRY_S_NAME.add("burundi")
        self._COUNTRY_S_NAME.add("slovakia")
        self._COUNTRY_S_NAME.add("uzbekistan")
        self._COUNTRY_S_NAME.add("maroc")
        self._COUNTRY_S_NAME.add("tanzania")
        self._COUNTRY_S_NAME.add("litva")
        self._COUNTRY_S_NAME.add("grenada")
        self._COUNTRY_S_NAME.add("gruzia")
        self._COUNTRY_S_NAME.add("lít-va")
        self._COUNTRY_S_NAME.add("guam")
        self._COUNTRY_S_NAME.add("eritrea")
        self._COUNTRY_S_NAME.add("áo")
        self._COUNTRY_S_NAME.add("croatia")
        self._COUNTRY_S_NAME.add("niue")
        self._COUNTRY_S_NAME.add("nepal")
        self._COUNTRY_S_NAME.add("tokelau")
        self._COUNTRY_S_NAME.add("bermuda")
        self._COUNTRY_S_NAME.add("i-rắc")
        self._COUNTRY_S_NAME.add("suriname")
        self._COUNTRY_S_NAME.add("guadeloupe")
        self._COUNTRY_S_NAME.add("nga")
        self._COUNTRY_S_NAME.add("romania")
        self._COUNTRY_S_NAME.add("angola")
        self._COUNTRY_S_NAME.add("latvia")
        self._COUNTRY_S_NAME.add("kazakhstan")
        self._COUNTRY_S_NAME.add("malta")
        self._COUNTRY_S_NAME.add("myanmar")
        self._COUNTRY_S_NAME.add("iceland")
        self._COUNTRY_S_NAME.add("românia")
        self._COUNTRY_S_NAME.add("montenegro")
        self._COUNTRY_S_NAME.add("macau")
        self._COUNTRY_S_NAME.add("tuvalu")
        self._COUNTRY_S_NAME.add("qatar")
        self._COUNTRY_S_NAME.add("tonga")
        self._COUNTRY_S_NAME.add("barbados")
        self._WORLD_COMPANY={"verizon"}
        self._WORLD_COMPANY.add("prada")
        self._WORLD_COMPANY.add("hp")
        self._WORLD_COMPANY.add("walmart")
        self._WORLD_COMPANY.add("adidas")
        self._WORLD_COMPANY.add("mastercard")
        self._WORLD_COMPANY.add("digg")
        self._WORLD_COMPANY.add("canon")
        self._WORLD_COMPANY.add("ikea")
        self._WORLD_COMPANY.add("sony")
        self._WORLD_COMPANY.add("twitter")
        self._WORLD_COMPANY.add("lego")
        self._WORLD_COMPANY.add("toshiba")
        self._WORLD_COMPANY.add("nokia")
        self._WORLD_COMPANY.add("bbc")
        self._WORLD_COMPANY.add("vmware")
        self._WORLD_COMPANY.add("mercedes-benz")
        self._WORLD_COMPANY.add("google")
        self._WORLD_COMPANY.add("intel")
        self._WORLD_COMPANY.add("iphone")
        self._WORLD_COMPANY.add("rbc")
        self._WORLD_COMPANY.add("fedex")
        self._WORLD_COMPANY.add("mercedes")
        self._WORLD_COMPANY.add("gillette")
        self._WORLD_COMPANY.add("ups")
        self._WORLD_COMPANY.add("carrefour")
        self._WORLD_COMPANY.add("lenovo")
        self._WORLD_COMPANY.add("loreal")
        self._WORLD_COMPANY.add("mcdonald")
        self._WORLD_COMPANY.add("coca-cola")
        self._WORLD_COMPANY.add("guardian")
        self._WORLD_COMPANY.add("cisco")
        self._WORLD_COMPANY.add("paypal")
        self._WORLD_COMPANY.add("cvs")
        self._WORLD_COMPANY.add("acer")
        self._WORLD_COMPANY.add("cnn")
        self._WORLD_COMPANY.add("nike")
        self._WORLD_COMPANY.add("facebook")
        self._WORLD_COMPANY.add("spotify")
        self._WORLD_COMPANY.add("adobe")
        self._WORLD_COMPANY.add("kfc")
        self._WORLD_COMPANY.add("westpac")
        self._WORLD_COMPANY.add("subway")
        self._WORLD_COMPANY.add("ibm")
        self._WORLD_COMPANY.add("panasonic")
        self._WORLD_COMPANY.add("visa")
        self._WORLD_COMPANY.add("motorola")
        self._WORLD_COMPANY.add("nissan")
        self._WORLD_COMPANY.add("citibank")
        self._WORLD_COMPANY.add("baidu")
        self._WORLD_COMPANY.add("ford")
        self._WORLD_COMPANY.add("microsoft")
        self._WORLD_COMPANY.add("bmw")
        self._WORLD_COMPANY.add("foxconn")
        self._WORLD_COMPANY.add("yahoo")
        self._WORLD_COMPANY.add("hermes")
        self._WORLD_COMPANY.add("oracle")
        self._WORLD_COMPANY.add("mcdonalds")
        self._WORLD_COMPANY.add("tencent")
        self._WORLD_COMPANY.add("mtv")
        self._WORLD_COMPANY.add("zara")
        self._WORLD_COMPANY.add("amazon")
        self._WORLD_COMPANY.add("toyota")
        self._WORLD_COMPANY.add("gucci")
        self._WORLD_COMPANY.add("ebay")
        self._WORLD_COMPANY.add("kodak")
        self._WORLD_COMPANY.add("youtube")
        self._WORLD_COMPANY.add("android")
        self._WORLD_COMPANY.add("linkedin")
        self._WORLD_COMPANY.add("myspace")
        self._WORLD_COMPANY.add("t-mobile")
        self._WORLD_COMPANY.add("apple")
        self._WORLD_COMPANY.add("samsung")
        self._WORLD_COMPANY.add("aldi")
        self._WORLD_COMPANY.add("colgate")
        self._WORLD_COMPANY.add("starbucks")
        self._WORLD_COMPANY.add("pepsi")
        self._WORLD_COMPANY.add("honda")
        self._WORLD_COMPANY.add("dell")
        self._WORLD_COMPANY.add("hitachi")
        self._WORLD_COMPANY.add("blackberry")
        self._WORLD_COMPANY.add("disney")
        self._WORLD_COMPANY.add("siemens")
        self._WORLD_COMPANY.add("vodafone")
        self._VN_LOCATIONS={"mỹ tho"}
        self._VN_LOCATIONS.add("nam đông")
        self._VN_LOCATIONS.add("kiên lương")
        self._VN_LOCATIONS.add("lương sơn")
        self._VN_LOCATIONS.add("gò vấp")
        self._VN_LOCATIONS.add("quang bình")
        self._VN_LOCATIONS.add("ia pa")
        self._VN_LOCATIONS.add("lạc sơn")
        self._VN_LOCATIONS.add("chí linh")
        self._VN_LOCATIONS.add("ninh hải")
        self._VN_LOCATIONS.add("sơn dương")
        self._VN_LOCATIONS.add("quan sơn")
        self._VN_LOCATIONS.add("ứng hoà")
        self._VN_LOCATIONS.add("krông pắk")
        self._VN_LOCATIONS.add("tân hưng")
        self._VN_LOCATIONS.add("nghệ an")
        self._VN_LOCATIONS.add("tân thạnh")
        self._VN_LOCATIONS.add("yên định")
        self._VN_LOCATIONS.add("mường nhé")
        self._VN_LOCATIONS.add("ngô quyền")
        self._VN_LOCATIONS.add("hàm thuận bắc")
        self._VN_LOCATIONS.add("phú tân")
        self._VN_LOCATIONS.add("tân hồng")
        self._VN_LOCATIONS.add("trà ôn")
        self._VN_LOCATIONS.add("từ liêm")
        self._VN_LOCATIONS.add("bình thuận")
        self._VN_LOCATIONS.add("an phú")
        self._VN_LOCATIONS.add("duy xuyên")
        self._VN_LOCATIONS.add("nam trực")
        self._VN_LOCATIONS.add("phù cừ")
        self._VN_LOCATIONS.add("mai sơn")
        self._VN_LOCATIONS.add("thạnh phú")
        self._VN_LOCATIONS.add("lộc bình")
        self._VN_LOCATIONS.add("kim thành")
        self._VN_LOCATIONS.add("cái bè")
        self._VN_LOCATIONS.add("hà quảng")
        self._VN_LOCATIONS.add("long thành")
        self._VN_LOCATIONS.add("đồng phù")
        self._VN_LOCATIONS.add("bảo yên")
        self._VN_LOCATIONS.add("chiêm hoá")
        self._VN_LOCATIONS.add("gia nghĩa")
        self._VN_LOCATIONS.add("an dương")
        self._VN_LOCATIONS.add("phú quý")
        self._VN_LOCATIONS.add("quảng trạch")
        self._VN_LOCATIONS.add("trường sa")
        self._VN_LOCATIONS.add("hoàn kiếm")
        self._VN_LOCATIONS.add("thủ thừa")
        self._VN_LOCATIONS.add("hải lăng")
        self._VN_LOCATIONS.add("pleiku")
        self._VN_LOCATIONS.add("thanh hoá")
        self._VN_LOCATIONS.add("bạch thông")
        self._VN_LOCATIONS.add("vĩnh phúc")
        self._VN_LOCATIONS.add("vãn lãng")
        self._VN_LOCATIONS.add("bình gia")
        self._VN_LOCATIONS.add("sa thầy")
        self._VN_LOCATIONS.add("triệu sơn")
        self._VN_LOCATIONS.add("yên thuỷ")
        self._VN_LOCATIONS.add("văn giang")
        self._VN_LOCATIONS.add("hồ chí minh")
        self._VN_LOCATIONS.add("nga sơn")
        self._VN_LOCATIONS.add("gia lâm")
        self._VN_LOCATIONS.add("vị thanh")
        self._VN_LOCATIONS.add("cái răng")
        self._VN_LOCATIONS.add("cao bằng")
        self._VN_LOCATIONS.add("hoài ân")
        self._VN_LOCATIONS.add("vĩnh long")
        self._VN_LOCATIONS.add("kim động")
        self._VN_LOCATIONS.add("ngân sơn")
        self._VN_LOCATIONS.add("lấp vò")
        self._VN_LOCATIONS.add("sông công")
        self._VN_LOCATIONS.add("hoài nhơn")
        self._VN_LOCATIONS.add("kim bôi")
        self._VN_LOCATIONS.add("bắc ninh")
        self._VN_LOCATIONS.add("thái nguyên")
        self._VN_LOCATIONS.add("đơn dương")
        self._VN_LOCATIONS.add("định quán")
        self._VN_LOCATIONS.add("gò công")
        self._VN_LOCATIONS.add("hà giang")
        self._VN_LOCATIONS.add("hoà bình")
        self._VN_LOCATIONS.add("mèo vạc")
        self._VN_LOCATIONS.add("mộc châu")
        self._VN_LOCATIONS.add("quảng ngãi")
        self._VN_LOCATIONS.add("cẩm giàng")
        self._VN_LOCATIONS.add("sông hinh")
        self._VN_LOCATIONS.add("thới bình")
        self._VN_LOCATIONS.add("phụng hiệp")
        self._VN_LOCATIONS.add("ninh hoà")
        self._VN_LOCATIONS.add("hậu giang")
        self._VN_LOCATIONS.add("cái nước")
        self._VN_LOCATIONS.add("ô môn")
        self._VN_LOCATIONS.add("gia lai")
        self._VN_LOCATIONS.add("phổ yên")
        self._VN_LOCATIONS.add("quế sơn")
        self._VN_LOCATIONS.add("yên thành")
        self._VN_LOCATIONS.add("tiên du")
        self._VN_LOCATIONS.add("an minh")
        self._VN_LOCATIONS.add("chợ lách")
        self._VN_LOCATIONS.add("phú ninh")
        self._VN_LOCATIONS.add("tủa chùa")
        self._VN_LOCATIONS.add("hương trà")
        self._VN_LOCATIONS.add("thăng bình")
        self._VN_LOCATIONS.add("vĩnh thuận")
        self._VN_LOCATIONS.add("hà tĩnh")
        self._VN_LOCATIONS.add("lâm đồng")
        self._VN_LOCATIONS.add("phú quốc")
        self._VN_LOCATIONS.add("long mỹ")
        self._VN_LOCATIONS.add("long an")
        self._VN_LOCATIONS.add("bình lục")
        self._VN_LOCATIONS.add("vĩnh thạnh")
        self._VN_LOCATIONS.add("đống đa")
        self._VN_LOCATIONS.add("hạ long")
        self._VN_LOCATIONS.add("kỳ sơn")
        self._VN_LOCATIONS.add("đăk song")
        self._VN_LOCATIONS.add("lai vung")
        self._VN_LOCATIONS.add("ý yên")
        self._VN_LOCATIONS.add("xuyên mộc")
        self._VN_LOCATIONS.add("vị xuyên")
        self._VN_LOCATIONS.add("duy tiên")
        self._VN_LOCATIONS.add("khánh sơn")
        self._VN_LOCATIONS.add("bỉm sơn")
        self._VN_LOCATIONS.add("hiệp đức")
        self._VN_LOCATIONS.add("kim sơn")
        self._VN_LOCATIONS.add("xín mần")
        self._VN_LOCATIONS.add("hương thuỷ")
        self._VN_LOCATIONS.add("tuy hoà")
        self._VN_LOCATIONS.add("u minh")
        self._VN_LOCATIONS.add("thiệu hoá")
        self._VN_LOCATIONS.add("bù đốp")
        self._VN_LOCATIONS.add("yên sơn")
        self._VN_LOCATIONS.add("quảng xương")
        self._VN_LOCATIONS.add("cần đước")
        self._VN_LOCATIONS.add("thuỷ nguyên")
        self._VN_LOCATIONS.add("yên dũng")
        self._VN_LOCATIONS.add("yên hưng")
        self._VN_LOCATIONS.add("bắc mê")
        self._VN_LOCATIONS.add("thọ xuân")
        self._VN_LOCATIONS.add("móng cái")
        self._VN_LOCATIONS.add("lạc dương")
        self._VN_LOCATIONS.add("cẩm xuyên")
        self._VN_LOCATIONS.add("lâm thao")
        self._VN_LOCATIONS.add("bình tân")
        self._VN_LOCATIONS.add("phúc yên")
        self._VN_LOCATIONS.add("sơn tây")
        self._VN_LOCATIONS.add("vĩnh châu")
        self._VN_LOCATIONS.add("na hang")
        self._VN_LOCATIONS.add("chương mỹ")
        self._VN_LOCATIONS.add("bảo lộc")
        self._VN_LOCATIONS.add("nghi xuân")
        self._VN_LOCATIONS.add("lương tài")
        self._VN_LOCATIONS.add("thoại sơn")
        self._VN_LOCATIONS.add("cửa lò")
        self._VN_LOCATIONS.add("đông hưng")
        self._VN_LOCATIONS.add("lập thạch")
        self._VN_LOCATIONS.add("nam định")
        self._VN_LOCATIONS.add("quảng nam")
        self._VN_LOCATIONS.add("kiên hải")
        self._VN_LOCATIONS.add("đồng xuân")
        self._VN_LOCATIONS.add("phú xuyên")
        self._VN_LOCATIONS.add("tiểu cần")
        self._VN_LOCATIONS.add("phúc thọ")
        self._VN_LOCATIONS.add("đông giang")
        self._VN_LOCATIONS.add("gò dầu")
        self._VN_LOCATIONS.add("giá rai")
        self._VN_LOCATIONS.add("tây sơn")
        self._VN_LOCATIONS.add("phú hoà")
        self._VN_LOCATIONS.add("việt yên")
        self._VN_LOCATIONS.add("đak đoa")
        self._VN_LOCATIONS.add("mường la")
        self._VN_LOCATIONS.add("hồng ngự")
        self._VN_LOCATIONS.add("bắc bình")
        self._VN_LOCATIONS.add("phủ lý")
        self._VN_LOCATIONS.add("gio linh")
        self._VN_LOCATIONS.add("cồn cỏ")
        self._VN_LOCATIONS.add("đức linh")
        self._VN_LOCATIONS.add("củ chi")
        self._VN_LOCATIONS.add("hương sơn")
        self._VN_LOCATIONS.add("tịnh biên")
        self._VN_LOCATIONS.add("bình thuỷ")
        self._VN_LOCATIONS.add("nhà bè")
        self._VN_LOCATIONS.add("yên thế")
        self._VN_LOCATIONS.add("vĩnh tường")
        self._VN_LOCATIONS.add("kế sách")
        self._VN_LOCATIONS.add("sóc sơn")
        self._VN_LOCATIONS.add("chợ đồn")
        self._VN_LOCATIONS.add("châu phú")
        self._VN_LOCATIONS.add("kiến an")
        self._VN_LOCATIONS.add("sốp cộp")
        self._VN_LOCATIONS.add("lệ thuỷ")
        self._VN_LOCATIONS.add("sơn tịnh")
        self._VN_LOCATIONS.add("càng long")
        self._VN_LOCATIONS.add("vị thuỷ")
        self._VN_LOCATIONS.add("ea súp")
        self._VN_LOCATIONS.add("quảng điền")
        self._VN_LOCATIONS.add("nghĩa lộ")
        self._VN_LOCATIONS.add("đồ sơn")
        self._VN_LOCATIONS.add("krông pa")
        self._VN_LOCATIONS.add("việt trì")
        self._VN_LOCATIONS.add("tân thành")
        self._VN_LOCATIONS.add("nghĩa hưng")
        self._VN_LOCATIONS.add("bạc liêu")
        self._VN_LOCATIONS.add("hưng yên")
        self._VN_LOCATIONS.add("hoàng mai")
        self._VN_LOCATIONS.add("diên khánh")
        self._VN_LOCATIONS.add("lăk")
        self._VN_LOCATIONS.add("bắc trà my")
        self._VN_LOCATIONS.add("tân châu")
        self._VN_LOCATIONS.add("tân phú")
        self._VN_LOCATIONS.add("bình long")
        self._VN_LOCATIONS.add("đông hà")
        self._VN_LOCATIONS.add("kon plông")
        self._VN_LOCATIONS.add("sa đéc")
        self._VN_LOCATIONS.add("an lão")
        self._VN_LOCATIONS.add("như xuân")
        self._VN_LOCATIONS.add("bến lức")
        self._VN_LOCATIONS.add("thanh khê")
        self._VN_LOCATIONS.add("long xuyên")
        self._VN_LOCATIONS.add("chợ gạo")
        self._VN_LOCATIONS.add("lục nam")
        self._VN_LOCATIONS.add("hoà thành")
        self._VN_LOCATIONS.add("vũng liêm")
        self._VN_LOCATIONS.add("bình định")
        self._VN_LOCATIONS.add("cẩm mỹ")
        self._VN_LOCATIONS.add("mộc hoá")
        self._VN_LOCATIONS.add("tánh linh")
        self._VN_LOCATIONS.add("đất đỏ")
        self._VN_LOCATIONS.add("quế võ")
        self._VN_LOCATIONS.add("trấn yên")
        self._VN_LOCATIONS.add("cầu ngang")
        self._VN_LOCATIONS.add("lai châu")
        self._VN_LOCATIONS.add("gò công tây")
        self._VN_LOCATIONS.add("lý nhân")
        self._VN_LOCATIONS.add("bà rịa-vũng tàu")
        self._VN_LOCATIONS.add("bình giang")
        self._VN_LOCATIONS.add("mường khương")
        self._VN_LOCATIONS.add("gò quao")
        self._VN_LOCATIONS.add("bình đại")
        self._VN_LOCATIONS.add("điện bàn")
        self._VN_LOCATIONS.add("hải châu")
        self._VN_LOCATIONS.add("bắc giang")
        self._VN_LOCATIONS.add("văn lâm")
        self._VN_LOCATIONS.add("ninh thuận")
        self._VN_LOCATIONS.add("cô tô")
        self._VN_LOCATIONS.add("quảng uyên")
        self._VN_LOCATIONS.add("đông hải")
        self._VN_LOCATIONS.add("phan thiết")
        self._VN_LOCATIONS.add("tĩnh gia")
        self._VN_LOCATIONS.add("bạch long vĩ")
        self._VN_LOCATIONS.add("hoài đức")
        self._VN_LOCATIONS.add("la gi")
        self._VN_LOCATIONS.add("ngọc hồi")
        self._VN_LOCATIONS.add("bình sơn")
        self._VN_LOCATIONS.add("dương minh châu")
        self._VN_LOCATIONS.add("can lộc")
        self._VN_LOCATIONS.add("hồng bàng")
        self._VN_LOCATIONS.add("thanh miện")
        self._VN_LOCATIONS.add("trảng bàng")
        self._VN_LOCATIONS.add("thái bình")
        self._VN_LOCATIONS.add("hải dương")
        self._VN_LOCATIONS.add("hà tây")
        self._VN_LOCATIONS.add("krông nô")
        self._VN_LOCATIONS.add("tam đường")
        self._VN_LOCATIONS.add("nguyên bình")
        self._VN_LOCATIONS.add("thủ dầu một")
        self._VN_LOCATIONS.add("vĩnh lộc")
        self._VN_LOCATIONS.add("đăk r'lấp")
        self._VN_LOCATIONS.add("hai bà trưng")
        self._VN_LOCATIONS.add("long khánh")
        self._VN_LOCATIONS.add("bình liêu")
        self._VN_LOCATIONS.add("đồng hỷ")
        self._VN_LOCATIONS.add("võ nhai")
        self._VN_LOCATIONS.add("lạc thuỷ")
        self._VN_LOCATIONS.add("quỳnh phụ")
        self._VN_LOCATIONS.add("diễn châu")
        self._VN_LOCATIONS.add("cầu giấy")
        self._VN_LOCATIONS.add("sơn la")
        self._VN_LOCATIONS.add("sông mã")
        self._VN_LOCATIONS.add("kinh môn")
        self._VN_LOCATIONS.add("thạch thành")
        self._VN_LOCATIONS.add("ea kar")
        self._VN_LOCATIONS.add("krông búk")
        self._VN_LOCATIONS.add("gò công đông")
        self._VN_LOCATIONS.add("phù ninh")
        self._VN_LOCATIONS.add("sơn hà")
        self._VN_LOCATIONS.add("đạ tẻh")
        self._VN_LOCATIONS.add("mộ đức")
        self._VN_LOCATIONS.add("cờ đỏ")
        self._VN_LOCATIONS.add("hương khê")
        self._VN_LOCATIONS.add("phú lương")
        self._VN_LOCATIONS.add("di linh")
        self._VN_LOCATIONS.add("phú vang")
        self._VN_LOCATIONS.add("lạng giang")
        self._VN_LOCATIONS.add("yên mô")
        self._VN_LOCATIONS.add("giao thuỷ")
        self._VN_LOCATIONS.add("quốc oai")
        self._VN_LOCATIONS.add("tuyên quang")
        self._VN_LOCATIONS.add("bát xát")
        self._VN_LOCATIONS.add("bắc hà")
        self._VN_LOCATIONS.add("đắk lắk")
        self._VN_LOCATIONS.add("tiên phước")
        self._VN_LOCATIONS.add("lê chân")
        self._VN_LOCATIONS.add("tiên yên")
        self._VN_LOCATIONS.add("bến cát")
        self._VN_LOCATIONS.add("tây giang")
        self._VN_LOCATIONS.add("đà nẵng")
        self._VN_LOCATIONS.add("ia grai")
        self._VN_LOCATIONS.add("tam bình")
        self._VN_LOCATIONS.add("thường tín")
        self._VN_LOCATIONS.add("vĩnh bảo")
        self._VN_LOCATIONS.add("hướng hoá")
        self._VN_LOCATIONS.add("sơn trà")
        self._VN_LOCATIONS.add("tân uyên")
        self._VN_LOCATIONS.add("m'đrăk")
        self._VN_LOCATIONS.add("quản bạ")
        self._VN_LOCATIONS.add("liên chiểu")
        self._VN_LOCATIONS.add("tri tôn")
        self._VN_LOCATIONS.add("tiên lãng")
        self._VN_LOCATIONS.add("biên hoà")
        self._VN_LOCATIONS.add("hải hậu")
        self._VN_LOCATIONS.add("tây ninh")
        self._VN_LOCATIONS.add("quỳnh nhai")
        self._VN_LOCATIONS.add("thạch hà")
        self._VN_LOCATIONS.add("đồng nai")
        self._VN_LOCATIONS.add("tuyên hoá")
        self._VN_LOCATIONS.add("mai châu")
        self._VN_LOCATIONS.add("yên bái")
        self._VN_LOCATIONS.add("duyên hải")
        self._VN_LOCATIONS.add("tháp mười")
        self._VN_LOCATIONS.add("phú nhuận")
        self._VN_LOCATIONS.add("ân thi")
        self._VN_LOCATIONS.add("khoái châu")
        self._VN_LOCATIONS.add("hòn đất")
        self._VN_LOCATIONS.add("thống nhất")
        self._VN_LOCATIONS.add("nghĩa đàn")
        self._VN_LOCATIONS.add("quế phong")
        self._VN_LOCATIONS.add("thủ đức")
        self._VN_LOCATIONS.add("hạ lang")
        self._VN_LOCATIONS.add("vĩnh linh")
        self._VN_LOCATIONS.add("yên lạc")
        self._VN_LOCATIONS.add("triệu phong")
        self._VN_LOCATIONS.add("lâm hà")
        self._VN_LOCATIONS.add("bảo lâm")
        self._VN_LOCATIONS.add("hải phòng")
        self._VN_LOCATIONS.add("vũ quang")
        self._VN_LOCATIONS.add("cao lộc")
        self._VN_LOCATIONS.add("nhơn trạch")
        self._VN_LOCATIONS.add("quảng trị")
        self._VN_LOCATIONS.add("thạch thất")
        self._VN_LOCATIONS.add("chơn thành")
        self._VN_LOCATIONS.add("tân yên")
        self._VN_LOCATIONS.add("thanh hà")
        self._VN_LOCATIONS.add("thạnh hoá")
        self._VN_LOCATIONS.add("si ma cai")
        self._VN_LOCATIONS.add("bác ái")
        self._VN_LOCATIONS.add("đăk hà")
        self._VN_LOCATIONS.add("yên minh")
        self._VN_LOCATIONS.add("tân bình")
        self._VN_LOCATIONS.add("đại từ")
        self._VN_LOCATIONS.add("phục hoà")
        self._VN_LOCATIONS.add("ninh sơn")
        self._VN_LOCATIONS.add("long phú")
        self._VN_LOCATIONS.add("hà tiên")
        self._VN_LOCATIONS.add("thanh bình")
        self._VN_LOCATIONS.add("mỏ cày")
        self._VN_LOCATIONS.add("thạnh trị")
        self._VN_LOCATIONS.add("trà vinh")
        self._VN_LOCATIONS.add("dầu tiếng")
        self._VN_LOCATIONS.add("bắc kạn")
        self._VN_LOCATIONS.add("chư sê")
        self._VN_LOCATIONS.add("thanh trì")
        self._VN_LOCATIONS.add("ngọc lạc")
        self._VN_LOCATIONS.add("từ sơn")
        self._VN_LOCATIONS.add("gia bình")
        self._VN_LOCATIONS.add("pác nặm")
        self._VN_LOCATIONS.add("thốt nốt")
        self._VN_LOCATIONS.add("trà bồng")
        self._VN_LOCATIONS.add("thừa thiên-huế")
        self._VN_LOCATIONS.add("phước long")
        self._VN_LOCATIONS.add("cẩm phả")
        self._VN_LOCATIONS.add("kon rẫy")
        self._VN_LOCATIONS.add("long biên")
        self._VN_LOCATIONS.add("cư m'gar")
        self._VN_LOCATIONS.add("cao lãnh")
        self._VN_LOCATIONS.add("buôn đôn")
        self._VN_LOCATIONS.add("đắk nông")
        self._VN_LOCATIONS.add("lý sơn")
        self._VN_LOCATIONS.add("sóc trăng")
        self._VN_LOCATIONS.add("hoằng hoá")
        self._VN_LOCATIONS.add("quận 10")
        self._VN_LOCATIONS.add("krông ana")
        self._VN_LOCATIONS.add("quận 11")
        self._VN_LOCATIONS.add("quận 12")
        self._VN_LOCATIONS.add("phan rang-tháp chàm")
        self._VN_LOCATIONS.add("tân kỳ")
        self._VN_LOCATIONS.add("tương dương")
        self._VN_LOCATIONS.add("đan phượng")
        self._VN_LOCATIONS.add("anh sơn")
        self._VN_LOCATIONS.add("quận 2")
        self._VN_LOCATIONS.add("quận 1")
        self._VN_LOCATIONS.add("qui nhơn")
        self._VN_LOCATIONS.add("tư nghĩa")
        self._VN_LOCATIONS.add("bố trạch")
        self._VN_LOCATIONS.add("quận 9")
        self._VN_LOCATIONS.add("thạch an")
        self._VN_LOCATIONS.add("bảo thắng")
        self._VN_LOCATIONS.add("quận 8")
        self._VN_LOCATIONS.add("quận 7")
        self._VN_LOCATIONS.add("nghĩa hành")
        self._VN_LOCATIONS.add("quận 6")
        self._VN_LOCATIONS.add("quận 5")
        self._VN_LOCATIONS.add("hội an")
        self._VN_LOCATIONS.add("quận 4")
        self._VN_LOCATIONS.add("quận 3")
        self._VN_LOCATIONS.add("phong điền")
        self._VN_LOCATIONS.add("xuân lộc")
        self._VN_LOCATIONS.add("côn đảo")
        self._VN_LOCATIONS.add("nha trang")
        self._VN_LOCATIONS.add("tân lạc")
        self._VN_LOCATIONS.add("hạ hoà")
        self._VN_LOCATIONS.add("gia viễn")
        self._VN_LOCATIONS.add("đồng tháp")
        self._VN_LOCATIONS.add("hoành bồ")
        self._VN_LOCATIONS.add("bắc quang")
        self._VN_LOCATIONS.add("na rì")
        self._VN_LOCATIONS.add("sông cầu")
        self._VN_LOCATIONS.add("mường tè")
        self._VN_LOCATIONS.add("yên phong")
        self._VN_LOCATIONS.add("tứ kỳ")
        self._VN_LOCATIONS.add("vũ thư")
        self._VN_LOCATIONS.add("mỹ hào")
        self._VN_LOCATIONS.add("chư prông")
        self._VN_LOCATIONS.add("hóc môn")
        self._VN_LOCATIONS.add("châu đốc")
        self._VN_LOCATIONS.add("đô lương")
        self._VN_LOCATIONS.add("mang thít")
        self._VN_LOCATIONS.add("tràng định")
        self._VN_LOCATIONS.add("cam ranh")
        self._VN_LOCATIONS.add("mang yang")
        self._VN_LOCATIONS.add("hàm thuận nam")
        self._VN_LOCATIONS.add("hưng nguyên")
        self._VN_LOCATIONS.add("kiến xương")
        self._VN_LOCATIONS.add("ninh phước")
        self._VN_LOCATIONS.add("phong thổ")
        self._VN_LOCATIONS.add("đức thọ")
        self._VN_LOCATIONS.add("hồng lĩnh")
        self._VN_LOCATIONS.add("khánh vĩnh")
        self._VN_LOCATIONS.add("mỹ lộc")
        self._VN_LOCATIONS.add("ngọc hiển")
        self._VN_LOCATIONS.add("phước sơn")
        self._VN_LOCATIONS.add("hà đông")
        self._VN_LOCATIONS.add("lào cai")
        self._VN_LOCATIONS.add("vĩnh yên")
        self._VN_LOCATIONS.add("quỳ châu")
        self._VN_LOCATIONS.add("sơn động")
        self._VN_LOCATIONS.add("bến cầu")
        self._VN_LOCATIONS.add("đông anh")
        self._VN_LOCATIONS.add("kông chro")
        self._VN_LOCATIONS.add("trảng bom")
        self._VN_LOCATIONS.add("đông triều")
        self._VN_LOCATIONS.add("ba tơ")
        self._VN_LOCATIONS.add("cù lao dung")
        self._VN_LOCATIONS.add("mỹ xuyên")
        self._VN_LOCATIONS.add("quảng hà")
        self._VN_LOCATIONS.add("tân biên")
        self._VN_LOCATIONS.add("bá thước")
        self._VN_LOCATIONS.add("cà mau")
        self._VN_LOCATIONS.add("chi lăng")
        self._VN_LOCATIONS.add("yên bình")
        self._VN_LOCATIONS.add("bình minh")
        self._VN_LOCATIONS.add("bình dương")
        self._VN_LOCATIONS.add("an nhơn")
        self._VN_LOCATIONS.add("chư păh")
        self._VN_LOCATIONS.add("việt nam")
        self._VN_LOCATIONS.add("giồng riềng")
        self._VN_LOCATIONS.add("cát tiên")
        self._VN_LOCATIONS.add("thuận an")
        self._VN_LOCATIONS.add("ngã năm")
        self._VN_LOCATIONS.add("cẩm thuỷ")
        self._VN_LOCATIONS.add("minh long")
        self._VN_LOCATIONS.add("nam đàn")
        self._VN_LOCATIONS.add("tân hiệp")
        self._VN_LOCATIONS.add("thanh sơn")
        self._VN_LOCATIONS.add("dĩ an")
        self._VN_LOCATIONS.add("thuận thành")
        self._VN_LOCATIONS.add("điện biên phủ")
        self._VN_LOCATIONS.add("vạn ninh")
        self._VN_LOCATIONS.add("hưng yê")
        self._VN_LOCATIONS.add("thái thuỵ")
        self._VN_LOCATIONS.add("thanh xuân")
        self._VN_LOCATIONS.add("cần giờ")
        self._VN_LOCATIONS.add("ngũ hành sơn")
        self._VN_LOCATIONS.add("ba tri")
        self._VN_LOCATIONS.add("hồng dân")
        self._VN_LOCATIONS.add("ninh giang")
        self._VN_LOCATIONS.add("phan rang tháp chàm")
        self._VN_LOCATIONS.add("than uyên")
        self._VN_LOCATIONS.add("phú lộc")
        self._VN_LOCATIONS.add("thanh chương")
        self._VN_LOCATIONS.add("lục ngạn")
        self._VN_LOCATIONS.add("năm căn")
        self._VN_LOCATIONS.add("điện biên đông")
        self._VN_LOCATIONS.add("hữu lũng")
        self._VN_LOCATIONS.add("hoàng su phì")
        self._VN_LOCATIONS.add("tây hồ")
        self._VN_LOCATIONS.add("bắc yên")
        self._VN_LOCATIONS.add("sài gòn")
        self._VN_LOCATIONS.add("vĩnh cửu")
        self._VN_LOCATIONS.add("bình phước")
        self._VN_LOCATIONS.add("nam sách")
        self._VN_LOCATIONS.add("hưng hà")
        self._VN_LOCATIONS.add("bình chánh")
        self._VN_LOCATIONS.add("uông bí")
        self._VN_LOCATIONS.add("ea h'leo")
        self._VN_LOCATIONS.add("tam điệp")
        self._VN_LOCATIONS.add("nam giang")
        self._VN_LOCATIONS.add("trùng khánh")
        self._VN_LOCATIONS.add("gia lộc")
        self._VN_LOCATIONS.add("tam dương")
        self._VN_LOCATIONS.add("hoà an")
        self._VN_LOCATIONS.add("thừa thiên huế")
        self._VN_LOCATIONS.add("nông cống")
        self._VN_LOCATIONS.add("tam kỳ")
        self._VN_LOCATIONS.add("đak pơ")
        self._VN_LOCATIONS.add("bình thạnh")
        self._VN_LOCATIONS.add("hà nội")
        self._VN_LOCATIONS.add("châu thành")
        self._VN_LOCATIONS.add("tiên lữ")
        self._VN_LOCATIONS.add("cầu kè")
        self._VN_LOCATIONS.add("ninh kiều")
        self._VN_LOCATIONS.add("buôn ma thuột")
        self._VN_LOCATIONS.add("an khê")
        self._VN_LOCATIONS.add("đức huệ")
        self._VN_LOCATIONS.add("tiền hải")
        self._VN_LOCATIONS.add("tuy phước")
        self._VN_LOCATIONS.add("bà rịa")
        self._VN_LOCATIONS.add("đa krông")
        self._VN_LOCATIONS.add("đồng xoài")
        self._VN_LOCATIONS.add("ba vì")
        self._VN_LOCATIONS.add("quảng ninh")
        self._VN_LOCATIONS.add("điện biên")
        self._VN_LOCATIONS.add("hà trung")
        self._VN_LOCATIONS.add("thanh oai")
        self._VN_LOCATIONS.add("trà cú")
        self._VN_LOCATIONS.add("văn yên")
        self._VN_LOCATIONS.add("bình xuyên")
        self._VN_LOCATIONS.add("hoà vang")
        self._VN_LOCATIONS.add("trà lĩnh")
        self._VN_LOCATIONS.add("yên khánh")
        self._VN_LOCATIONS.add("kbang")
        self._VN_LOCATIONS.add("hoàng sa")
        self._VN_LOCATIONS.add("văn quan")
        self._VN_LOCATIONS.add("ba chẽ")
        self._VN_LOCATIONS.add("nho quan")
        self._VN_LOCATIONS.add("khánh hoà")
        self._VN_LOCATIONS.add("đăk mil")
        self._VN_LOCATIONS.add("kiến thuỵ")
        self._VN_LOCATIONS.add("đầm hà")
        self._VN_LOCATIONS.add("hàm tân")
        self._VN_LOCATIONS.add("phù cát")
        self._VN_LOCATIONS.add("kim bảng")
        self._VN_LOCATIONS.add("vũng tầu")
        self._VN_LOCATIONS.add("kiên giang")
        self._VN_LOCATIONS.add("long hồ")
        self._VN_LOCATIONS.add("mường chà")
        self._VN_LOCATIONS.add("thanh ba")
        self._VN_LOCATIONS.add("đại lộc")
        self._VN_LOCATIONS.add("mê linh")
        self._VN_LOCATIONS.add("mường lát")
        self._VN_LOCATIONS.add("đạ huoai")
        self._VN_LOCATIONS.add("huế")
        self._VN_LOCATIONS.add("cần thơ")
        self._VN_LOCATIONS.add("vụ bản")
        self._VN_LOCATIONS.add("thanh liêm")
        self._VN_LOCATIONS.add("đoan hùng")
        self._VN_LOCATIONS.add("hiệp hoà")
        self._VN_LOCATIONS.add("bắc sơn")
        self._VN_LOCATIONS.add("tân trụ")
        self._VN_LOCATIONS.add("cần giuộc")
        self._VN_LOCATIONS.add("đăk glong")
        self._VN_LOCATIONS.add("hậu lộc")
        self._VN_LOCATIONS.add("kỳ anh")
        self._VN_LOCATIONS.add("cai lậy")
        self._VN_LOCATIONS.add("krông bông")
        self._VN_LOCATIONS.add("yên lập")
        self._VN_LOCATIONS.add("mù căng chải")
        self._VN_LOCATIONS.add("mỹ tú")
        self._VN_LOCATIONS.add("trạm tấu")
        self._VN_LOCATIONS.add("cư jút")
        self._VN_LOCATIONS.add("quỳ hợp")
        self._VN_LOCATIONS.add("tân phước")
        self._VN_LOCATIONS.add("vĩnh lợi")
        self._VN_LOCATIONS.add("đồng văn")
        self._VN_LOCATIONS.add("đông sơn")
        self._VN_LOCATIONS.add("tây trà")
        self._VN_LOCATIONS.add("lộc ninh")
        self._VN_LOCATIONS.add("sầm sơn")
        self._VN_LOCATIONS.add("lạng sơn")
        self._VN_LOCATIONS.add("sa pa")
        self._VN_LOCATIONS.add("hàm yên")
        self._VN_LOCATIONS.add("vân đồn")
        self._VN_LOCATIONS.add("đà bắc")
        self._VN_LOCATIONS.add("vân canh")
        self._VN_LOCATIONS.add("sơn hoà")
        self._VN_LOCATIONS.add("thuận bắc")
        self._VN_LOCATIONS.add("châu đức")
        self._VN_LOCATIONS.add("thường xuân")
        self._VN_LOCATIONS.add("định hoá")
        self._VN_LOCATIONS.add("giồng trôm")
        self._VN_LOCATIONS.add("núi thành")
        self._VN_LOCATIONS.add("rạch giá")
        self._VN_LOCATIONS.add("con cuông")
        self._VN_LOCATIONS.add("ninh bình")
        self._VN_LOCATIONS.add("đồng hới")
        self._VN_LOCATIONS.add("tân an")
        self._VN_LOCATIONS.add("trực ninh")
        self._VN_LOCATIONS.add("thuận châu")
        self._VN_LOCATIONS.add("vinh")
        self._VN_LOCATIONS.add("trần văn thời")
        self._VN_LOCATIONS.add("minh hoá")
        self._VN_LOCATIONS.add("yên mỹ")
        self._VN_LOCATIONS.add("quan hoá")
        self._VN_LOCATIONS.add("văn bàn")
        self._VN_LOCATIONS.add("cam lộ")
        self._VN_LOCATIONS.add("lang chánh")
        self._VN_LOCATIONS.add("phù yên")
        self._VN_LOCATIONS.add("đăk tô")
        self._VN_LOCATIONS.add("hoa lư")
        self._VN_LOCATIONS.add("lục yên")
        self._VN_LOCATIONS.add("đức phổ")
        self._VN_LOCATIONS.add("hà nam")
        self._VN_LOCATIONS.add("tuy an")
        self._VN_LOCATIONS.add("an giang")
        self._VN_LOCATIONS.add("ba bể")
        self._VN_LOCATIONS.add("xuân trường")
        self._VN_LOCATIONS.add("cát hải")
        self._VN_LOCATIONS.add("kon tum")
        self._VN_LOCATIONS.add("bù đăng")
        self._VN_LOCATIONS.add("krông năng")
        self._VN_LOCATIONS.add("an biên")
        self._VN_LOCATIONS.add("yên châu")
        self._VN_LOCATIONS.add("phú thọ")
        self._VN_LOCATIONS.add("tam nông")
        self._VN_LOCATIONS.add("quỳnh lưu")
        self._VN_LOCATIONS.add("đình lập")
        self._VN_LOCATIONS.add("nghi lộc")
        self._VN_LOCATIONS.add("chợ mới")
        self._VN_LOCATIONS.add("đức trọng")
        self._VN_LOCATIONS.add("đầm dơi")
        self._VN_LOCATIONS.add("long đất")
        self._VN_LOCATIONS.add("mường lay")
        self._VN_LOCATIONS.add("tiền giang")
        self._VN_LOCATIONS.add("thông nông")
        self._VN_LOCATIONS.add("phú yên")
        self._VN_LOCATIONS.add("quảng bình")
        self._VN_LOCATIONS.add("sìn hồ")
        self._VN_LOCATIONS.add("tuy phong")
        self._VN_LOCATIONS.add("ba đình")
        self._VN_LOCATIONS.add("phù mỹ")
        self._VN_LOCATIONS.add("đức hoà")
        self._VN_LOCATIONS.add("bảo lạc")
        self._VN_LOCATIONS.add("đăk glei")
        self._VN_LOCATIONS.add("bến tre")
        self._VN_LOCATIONS.add("như thanh")
        self._VN_LOCATIONS.add("thanh thuỷ")
        self._VN_LOCATIONS.add("đà lạt")
        self._VN_LOCATIONS.add("đức cơ")
        self._VN_LOCATIONS.add("văn chấn")
        self._VN_LOCATIONS.add("bà rịa vũng tàu")
        self._VN_LOCATIONS.add("vĩnh hưng")
        self._VN_LOCATIONS.add("cao phong")
        self._VN_LOCATIONS.add("nam trà my")
        self._VN_LOCATIONS.add("phú giáo")
        self._VN_LOCATIONS.add("phú bình")
        self._VN_LOCATIONS.add("ayun pa")
        self._VN_LOCATIONS.add("mỹ đức")
        self._VN_LOCATIONS.add("tuần giáo")
        self._VN_FIRST_SENT_WORDS={"được"}
        self._VN_FIRST_SENT_WORDS.add("cty")
        self._VN_FIRST_SENT_WORDS.add("mẹ")
        self._VN_FIRST_SENT_WORDS.add("trừ")
        self._VN_FIRST_SENT_WORDS.add("lên")
        self._VN_FIRST_SENT_WORDS.add("trưởng")
        self._VN_FIRST_SENT_WORDS.add("là")
        self._VN_FIRST_SENT_WORDS.add("chàng")
        self._VN_FIRST_SENT_WORDS.add("theo")
        self._VN_FIRST_SENT_WORDS.add("tên")
        self._VN_FIRST_SENT_WORDS.add("giờ")
        self._VN_FIRST_SENT_WORDS.add("biết")
        self._VN_FIRST_SENT_WORDS.add("già")
        self._VN_FIRST_SENT_WORDS.add("những")
        self._VN_FIRST_SENT_WORDS.add("thấy")
        self._VN_FIRST_SENT_WORDS.add("thương")
        self._VN_FIRST_SENT_WORDS.add("lang")
        self._VN_FIRST_SENT_WORDS.add("gái")
        self._VN_FIRST_SENT_WORDS.add("mà")
        self._VN_FIRST_SENT_WORDS.add("xóm")
        self._VN_FIRST_SENT_WORDS.add("má")
        self._VN_FIRST_SENT_WORDS.add("cầu")
        self._VN_FIRST_SENT_WORDS.add("khách")
        self._VN_FIRST_SENT_WORDS.add("nhánh")
        self._VN_FIRST_SENT_WORDS.add("hôm")
        self._VN_FIRST_SENT_WORDS.add("nhớ")
        self._VN_FIRST_SENT_WORDS.add("hạng")
        self._VN_FIRST_SENT_WORDS.add("huyện")
        self._VN_FIRST_SENT_WORDS.add("vậy")
        self._VN_FIRST_SENT_WORDS.add("nhà")
        self._VN_FIRST_SENT_WORDS.add("ấp")
        self._VN_FIRST_SENT_WORDS.add("sông")
        self._VN_FIRST_SENT_WORDS.add("thằng")
        self._VN_FIRST_SENT_WORDS.add("nài")
        self._VN_FIRST_SENT_WORDS.add("ngành")
        self._VN_FIRST_SENT_WORDS.add("nếu")
        self._VN_FIRST_SENT_WORDS.add("trời")
        self._VN_FIRST_SENT_WORDS.add("đảng")
        self._VN_FIRST_SENT_WORDS.add("vào")
        self._VN_FIRST_SENT_WORDS.add("thầy")
        self._VN_FIRST_SENT_WORDS.add("hai")
        self._VN_FIRST_SENT_WORDS.add("vùng")
        self._VN_FIRST_SENT_WORDS.add("chuyện")
        self._VN_FIRST_SENT_WORDS.add("nhìn")
        self._VN_FIRST_SENT_WORDS.add("tim")
        self._VN_FIRST_SENT_WORDS.add("cha")
        self._VN_FIRST_SENT_WORDS.add("sang")
        self._VN_FIRST_SENT_WORDS.add("bên")
        self._VN_FIRST_SENT_WORDS.add("đường")
        self._VN_FIRST_SENT_WORDS.add("cho")
        self._VN_FIRST_SENT_WORDS.add("bảng")
        self._VN_FIRST_SENT_WORDS.add("khi")
        self._VN_FIRST_SENT_WORDS.add("quận")
        self._VN_FIRST_SENT_WORDS.add("biển")
        self._VN_FIRST_SENT_WORDS.add("cu")
        self._VN_FIRST_SENT_WORDS.add("metro")
        self._VN_FIRST_SENT_WORDS.add("vốn")
        self._VN_FIRST_SENT_WORDS.add("đến")
        self._VN_FIRST_SENT_WORDS.add("năm")
        self._VN_FIRST_SENT_WORDS.add("khu")
        self._VN_FIRST_SENT_WORDS.add("đài")
        self._VN_FIRST_SENT_WORDS.add("miền")
        self._VN_FIRST_SENT_WORDS.add("việc")
        self._VN_FIRST_SENT_WORDS.add("do")
        self._VN_FIRST_SENT_WORDS.add("lập")
        self._VN_FIRST_SENT_WORDS.add("nghe")
        self._VN_FIRST_SENT_WORDS.add("mắt")
        self._VN_FIRST_SENT_WORDS.add("viện")
        self._VN_FIRST_SENT_WORDS.add("cả")
        self._VN_FIRST_SENT_WORDS.add("em")
        self._VN_FIRST_SENT_WORDS.add("rừng")
        self._VN_FIRST_SENT_WORDS.add("liệu")
        self._VN_FIRST_SENT_WORDS.add("bố")
        self._VN_FIRST_SENT_WORDS.add("bộ")
        self._VN_FIRST_SENT_WORDS.add("cháu")
        self._VN_FIRST_SENT_WORDS.add("riêng")
        self._VN_FIRST_SENT_WORDS.add("bà")
        self._VN_FIRST_SENT_WORDS.add("số")
        self._VN_FIRST_SENT_WORDS.add("chị")
        self._VN_FIRST_SENT_WORDS.add("người")
        self._VN_FIRST_SENT_WORDS.add("bé")
        self._VN_FIRST_SENT_WORDS.add("tàu")
        self._VN_FIRST_SENT_WORDS.add("làng")
        self._VN_FIRST_SENT_WORDS.add("cảng")
        self._VN_FIRST_SENT_WORDS.add("sở")
        self._VN_FIRST_SENT_WORDS.add("chiếc")
        self._VN_FIRST_SENT_WORDS.add("tết")
        self._VN_FIRST_SENT_WORDS.add("cậu")
        self._VN_FIRST_SENT_WORDS.add("luật")
        self._VN_FIRST_SENT_WORDS.add("chờ")
        self._VN_FIRST_SENT_WORDS.add("rời")
        self._VN_FIRST_SENT_WORDS.add("chắc")
        self._VN_FIRST_SENT_WORDS.add("hội")
        self._VN_FIRST_SENT_WORDS.add("chợ")
        self._VN_FIRST_SENT_WORDS.add("viên")
        self._VN_FIRST_SENT_WORDS.add("cụ")
        self._VN_FIRST_SENT_WORDS.add("nay")
        self._VN_FIRST_SENT_WORDS.add("thuốc")
        self._VN_FIRST_SENT_WORDS.add("bọn")
        self._VN_FIRST_SENT_WORDS.add("tờ")
        self._VN_FIRST_SENT_WORDS.add("phía")
        self._VN_FIRST_SENT_WORDS.add("chữ")
        self._VN_FIRST_SENT_WORDS.add("xe")
        self._VN_FIRST_SENT_WORDS.add("cò")
        self._VN_FIRST_SENT_WORDS.add("có")
        self._VN_FIRST_SENT_WORDS.add("cô")
        self._VN_FIRST_SENT_WORDS.add("dân")
        self._VN_FIRST_SENT_WORDS.add("nhóm")
        self._VN_FIRST_SENT_WORDS.add("song")
        self._VN_FIRST_SENT_WORDS.add("chú")
        self._VN_FIRST_SENT_WORDS.add("từ")
        self._VN_FIRST_SENT_WORDS.add("như")
        self._VN_FIRST_SENT_WORDS.add("ngày")
        self._VN_FIRST_SENT_WORDS.add("phim")
        self._VN_FIRST_SENT_WORDS.add("chính")
        self._VN_FIRST_SENT_WORDS.add("tân")
        self._VN_FIRST_SENT_WORDS.add("gặp")
        self._VN_FIRST_SENT_WORDS.add("các")
        self._VN_FIRST_SENT_WORDS.add("quê")
        self._VN_FIRST_SENT_WORDS.add("dì")
        self._VN_FIRST_SENT_WORDS.add("bởi")
        self._VN_FIRST_SENT_WORDS.add("quí")
        self._VN_FIRST_SENT_WORDS.add("về")
        self._VN_FIRST_SENT_WORDS.add("trại")
        self._VN_FIRST_SENT_WORDS.add("tại")
        self._VN_FIRST_SENT_WORDS.add("lão")
        self._VN_FIRST_SENT_WORDS.add("đảo")
        self._VN_FIRST_SENT_WORDS.add("nguyên")
        self._VN_FIRST_SENT_WORDS.add("còn")
        self._VN_FIRST_SENT_WORDS.add("tiếng")
        self._VN_FIRST_SENT_WORDS.add("dòng")
        self._VN_FIRST_SENT_WORDS.add("và")
        self._VN_FIRST_SENT_WORDS.add("hiện")
        self._VN_FIRST_SENT_WORDS.add("vợ")
        self._VN_FIRST_SENT_WORDS.add("thuyền")
        self._VN_FIRST_SENT_WORDS.add("vụ")
        self._VN_FIRST_SENT_WORDS.add("đoàn")
        self._VN_FIRST_SENT_WORDS.add("thành")
        self._VN_FIRST_SENT_WORDS.add("giới")
        self._VN_FIRST_SENT_WORDS.add("bến")
        self._VN_FIRST_SENT_WORDS.add("vì")
        self._VN_FIRST_SENT_WORDS.add("đi")
        self._VN_FIRST_SENT_WORDS.add("sân")
        self._VN_FIRST_SENT_WORDS.add("sâm")
        self._VN_FIRST_SENT_WORDS.add("con")
        self._VN_FIRST_SENT_WORDS.add("bác")
        self._VN_FIRST_SENT_WORDS.add("cùng")
        self._VN_FIRST_SENT_WORDS.add("báo")
        self._VN_FIRST_SENT_WORDS.add("chồng")
        self._VN_FIRST_SENT_WORDS.add("hàng")
        self._VN_FIRST_SENT_WORDS.add("đất")
        self._VN_FIRST_SENT_WORDS.add("mỗi")
        self._VN_FIRST_SENT_WORDS.add("núi")
        self._VN_FIRST_SENT_WORDS.add("phòng")
        self._VN_FIRST_SENT_WORDS.add("xã")
        self._VN_FIRST_SENT_WORDS.add("hồ")
        self._VN_FIRST_SENT_WORDS.add("ông")
        self._VN_FIRST_SENT_WORDS.add("giọng")
        self._VN_FIRST_SENT_WORDS.add("trường")
        self._VN_FIRST_SENT_WORDS.add("đèo")
        self._VN_FIRST_SENT_WORDS.add("trùm")
        self._VN_FIRST_SENT_WORDS.add("nhiều")
        self._VN_FIRST_SENT_WORDS.add("thư")
        self._VN_FIRST_SENT_WORDS.add("cục")
        self._VN_FIRST_SENT_WORDS.add("nước")
        self._VN_FIRST_SENT_WORDS.add("thôn")
        self._VN_FIRST_SENT_WORDS.add("bạn")
        self._VN_FIRST_SENT_WORDS.add("nàng")
        self._VN_FIRST_SENT_WORDS.add("bệnh")
        self._VN_FIRST_SENT_WORDS.add("cụm")
        self._VN_FIRST_SENT_WORDS.add("tướng")
        self._VN_FIRST_SENT_WORDS.add("buôn")
        self._VN_FIRST_SENT_WORDS.add("để")
        self._VN_FIRST_SENT_WORDS.add("anh")
        self._VN_FIRST_SENT_WORDS.add("lính")
        self._VN_FIRST_SENT_WORDS.add("với")
        self._VN_FIRST_SENT_WORDS.add("ngoài")
        self._VN_FIRST_SENT_WORDS.add("trên")
        self._VN_FIRST_SENT_WORDS.add("hỏi")
        self._VN_FIRST_SENT_WORDS.add("sau")
        self._VN_FIRST_SENT_WORDS.add("đội")
        self._VN_FIRST_SENT_WORDS.add("gọi")
        self._VN_FIRST_SENT_WORDS.add("rồi")
        self._VN_FIRST_SENT_WORDS.add("một")
        self._VN_FIRST_SENT_WORDS.add("chúc")
        self._VN_FIRST_SENT_WORDS.add("nhưng")
        self._VN_FIRST_SENT_WORDS.add("đêm")
        self._VN_FIRST_SENT_WORDS.add("phó")
        self._VN_FIRST_SENT_WORDS.add("bỗng")
        self._VN_FIRST_SENT_WORDS.add("trong")
        self._VN_FIRST_SENT_WORDS.add("trước")
        self._VN_FIRST_SENT_WORDS.add("bản")
        self._VN_FIRST_SENT_WORDS.add("cuốn")
        self._VN_FIRST_SENT_WORDS.add("chùa")
        self._VN_FIRST_SENT_WORDS.add("ban")
        self._VN_FIRST_SENT_WORDS.add("giữa")
        self._VN_FIRST_SENT_WORDS.add("ngay")
        self._VN_FIRST_SENT_WORDS.add("lúc")
        self._VN_FIRST_SENT_WORDS.add("tỉnh")
        self._VN_FIRST_SENT_WORDS.add("tuy")
        self._VN_FIRST_SENT_WORDS.add("vẫn")

        self._VN_FIRST_SENT_WORDS.add("trà")
        self._VN_FIRST_SENT_WORDS.add("ôi")
        self._VN_FIRST_SENT_WORDS.add("cặp")
        self._VN_FIRST_SENT_WORDS.add("taxi")
        self._VN_FIRST_SENT_WORDS.add("nhiễm")
        self._VN_FIRST_SENT_WORDS.add("virus")
        self._VN_FIRST_SENT_WORDS.add("hồi")
        self._VN_FIRST_SENT_WORDS.add("nghĩa")
        self._VN_FIRST_SENT_WORDS.add("đọc")
        self._VN_FIRST_SENT_WORDS.add("nhờ")
        self._VN_FIRST_SENT_WORDS.add("tới")
        self._VN_FIRST_SENT_WORDS.add("ong")
        self._VN_FIRST_SENT_WORDS.add("website")
        self._VN_FIRST_SENT_WORDS.add("bóng")
        self._VN_FIRST_SENT_WORDS.add("quít")
        self._VN_FIRST_SENT_WORDS.add("kungfu")
        self._VN_FIRST_SENT_WORDS.add("ra")
        self._VN_FIRST_SENT_WORDS.add("đồng")
        self._VN_FIRST_SENT_WORDS.add("băng")
        self._VN_FIRST_SENT_WORDS.add("ba")
        self._VN_FIRST_SENT_WORDS.add("bầu")
        self._VN_FIRST_SENT_WORDS.add("hay")
        self._VN_FIRST_SENT_WORDS.add("giải")
        self._VN_FIRST_SENT_WORDS.add("giao")
        self._VN_FIRST_SENT_WORDS.add("cửa")
        self._VN_FIRST_SENT_WORDS.add("phần")
        self._VN_FIRST_SENT_WORDS.add("sinh")
        self._VN_FIRST_SENT_WORDS.add("vietcombank")
        self._VN_FIRST_SENT_WORDS.add("vàng")
        self._VN_FIRST_SENT_WORDS.add("fred")
        self._VN_FIRST_SENT_WORDS.add("tập")
        self._VN_FIRST_SENT_WORDS.add("toyota")
        self._VN_FIRST_SENT_WORDS.add("bế")
        self._VN_FIRST_SENT_WORDS.add("tuồng")
        self._VN_FIRST_SENT_WORDS.add("nguồn")
        self._VN_FIRST_SENT_WORDS.add("phường")
        self._VN_FIRST_SENT_WORDS.add("làm")
        self._VN_FIRST_SENT_WORDS.add("tuyển")
        self._VN_FIRST_SENT_WORDS.add("đền")
        self._VN_FIRST_SENT_WORDS.add("mong")
        self._VN_FIRST_SENT_WORDS.add("nghỉ")
        self._VN_FIRST_SENT_WORDS.add("hầm")
        self._VN_FIRST_SENT_WORDS.add("trán")
        self._VN_FIRST_SENT_WORDS.add("dắt")
        self._VN_FIRST_SENT_WORDS.add("sợ")
        self._VN_FIRST_SENT_WORDS.add("chỗ")
        self._VN_FIRST_SENT_WORDS.add("lái")
        self._VN_FIRST_SENT_WORDS.add("xem")
        self._VN_FIRST_SENT_WORDS.add("chủ")
        self._VN_FIRST_SENT_WORDS.add("chứ")
        self._VN_FIRST_SENT_WORDS.add("đợt")
        self._VN_FIRST_SENT_WORDS.add("đoạn")
        self._VN_FIRST_SENT_WORDS.add("đồn")
        self._VN_FIRST_SENT_WORDS.add("trục")
        self._VN_FIRST_SENT_WORDS.add("tự")
        self._VN_FIRST_SENT_WORDS.add("neil")
        self._VN_FIRST_SENT_WORDS.add("điện")
        self._VN_FIRST_SENT_WORDS.add("trạm")
        self._VN_FIRST_SENT_WORDS.add("gần")
        self._VN_FIRST_SENT_WORDS.add("giặc")
        self._VN_FIRST_SENT_WORDS.add("cúng")
        self._VN_FIRST_SENT_WORDS.add("dù")
        self._VN_FIRST_SENT_WORDS.add("vịnh")
        self._VN_FIRST_SENT_WORDS.add("quân")
        self._VN_FIRST_SENT_WORDS.add("dãy")
        self._VN_FIRST_SENT_WORDS.add("pha")
        self._VN_FIRST_SENT_WORDS.add("toàn")
        self._VN_FIRST_SENT_WORDS.add("tháp")
        self._VN_FIRST_SENT_WORDS.add("quĩ")
        self._VN_FIRST_SENT_WORDS.add("đĩa")
        self._VN_FIRST_SENT_WORDS.add("gà")
        self._VN_FIRST_SENT_WORDS.add("lao")
        self._VN_FIRST_SENT_WORDS.add("bốn")
        self._VN_FIRST_SENT_WORDS.add("họ")
        self._VN_FIRST_SENT_WORDS.add("họp")
        self._VN_FIRST_SENT_WORDS.add("đèn")
        self._VN_FIRST_SENT_WORDS.add("cũng")
        self._VN_FIRST_SENT_WORDS.add("động")
        self._VN_FIRST_SENT_WORDS.add("mặt")
        self._VN_FIRST_SENT_WORDS.add("đầm")
        self._VN_FIRST_SENT_WORDS.add("cống")
        self._VN_FIRST_SENT_WORDS.add("nơi")
        self._VN_FIRST_SENT_WORDS.add("tùng")
        self._VN_FIRST_SENT_WORDS.add("phố")
        self._VN_FIRST_SENT_WORDS.add("đầu")
        self._VN_FIRST_SENT_WORDS.add("vượt")
        self._VN_FIRST_SENT_WORDS.add("sao")
        self._VN_FIRST_SENT_WORDS.add("cách")
        self._VN_FIRST_SENT_WORDS.add("hoặc")
        self._VN_FIRST_SENT_WORDS.add("của")
        self._VN_FIRST_SENT_WORDS.add("hết")
        self._VN_FIRST_SENT_WORDS.add("đỉnh")
        self._VN_FIRST_SENT_WORDS.add("kênh")
        self._VN_FIRST_SENT_WORDS.add("quyền")
        self._VN_FIRST_SENT_WORDS.add("bar")
        self._VN_FIRST_SENT_WORDS.add("chống")
        self._VN_FIRST_SENT_WORDS.add("khắp")
        self._VN_FIRST_SENT_WORDS.add("sách")
        self._VN_FIRST_SENT_WORDS.add("wikipedia")
        self._VN_MIDDLE_NAMES={"thúy"}
        self._VN_MIDDLE_NAMES.add("bao")
        self._VN_MIDDLE_NAMES.add("thùy")
        self._VN_MIDDLE_NAMES.add("mạnh")
        self._VN_MIDDLE_NAMES.add("mỹ")
        self._VN_MIDDLE_NAMES.add("an")
        self._VN_MIDDLE_NAMES.add("hoa")
        self._VN_MIDDLE_NAMES.add("nữ")
        self._VN_MIDDLE_NAMES.add("trường")
        self._VN_MIDDLE_NAMES.add("vĩnh")
        self._VN_MIDDLE_NAMES.add("đắc")
        self._VN_MIDDLE_NAMES.add("minh")
        self._VN_MIDDLE_NAMES.add("thanh")
        self._VN_MIDDLE_NAMES.add("thi")
        self._VN_MIDDLE_NAMES.add("thu")
        self._VN_MIDDLE_NAMES.add("ninh")
        self._VN_MIDDLE_NAMES.add("đình")
        self._VN_MIDDLE_NAMES.add("hải")
        self._VN_MIDDLE_NAMES.add("tuấn")
        self._VN_MIDDLE_NAMES.add("bội")
        self._VN_MIDDLE_NAMES.add("thuý")
        self._VN_MIDDLE_NAMES.add("việt")
        self._VN_MIDDLE_NAMES.add("nguyễn")
        self._VN_MIDDLE_NAMES.add("bá")
        self._VN_MIDDLE_NAMES.add("phương")
        self._VN_MIDDLE_NAMES.add("bé")
        self._VN_MIDDLE_NAMES.add("tố")
        self._VN_MIDDLE_NAMES.add("quốc")
        self._VN_MIDDLE_NAMES.add("nguyệt")
        self._VN_MIDDLE_NAMES.add("tử")
        self._VN_MIDDLE_NAMES.add("cảnh")
        self._VN_MIDDLE_NAMES.add("trọng")
        self._VN_MIDDLE_NAMES.add("huy")
        self._VN_MIDDLE_NAMES.add("nam")
        self._VN_MIDDLE_NAMES.add("chí")
        self._VN_MIDDLE_NAMES.add("thái")
        self._VN_MIDDLE_NAMES.add("thành")
        self._VN_MIDDLE_NAMES.add("chính")
        self._VN_MIDDLE_NAMES.add("đinh")
        self._VN_MIDDLE_NAMES.add("mai")
        self._VN_MIDDLE_NAMES.add("thiên")
        self._VN_MIDDLE_NAMES.add("tôn")
        self._VN_MIDDLE_NAMES.add("phi")
        self._VN_MIDDLE_NAMES.add("hà")
        self._VN_MIDDLE_NAMES.add("khắc")
        self._VN_MIDDLE_NAMES.add("trúc")
        self._VN_MIDDLE_NAMES.add("lan")
        self._VN_MIDDLE_NAMES.add("doãn")
        self._VN_MIDDLE_NAMES.add("nhất")
        self._VN_MIDDLE_NAMES.add("huỳnh")
        self._VN_MIDDLE_NAMES.add("quỳnh")
        self._VN_MIDDLE_NAMES.add("diễm")
        self._VN_MIDDLE_NAMES.add("khánh")
        self._VN_MIDDLE_NAMES.add("hữu")
        self._VN_MIDDLE_NAMES.add("tấn")
        self._VN_MIDDLE_NAMES.add("anh")
        self._VN_MIDDLE_NAMES.add("hoành")
        self._VN_MIDDLE_NAMES.add("hoàng")
        self._VN_MIDDLE_NAMES.add("diệu")
        self._VN_MIDDLE_NAMES.add("lê")
        self._VN_MIDDLE_NAMES.add("phú")
        self._VN_MIDDLE_NAMES.add("duy")
        self._VN_MIDDLE_NAMES.add("bảo")
        self._VN_MIDDLE_NAMES.add("huyền")
        self._VN_MIDDLE_NAMES.add("nguyên")
        self._VN_MIDDLE_NAMES.add("bích")
        self._VN_MIDDLE_NAMES.add("ánh")
        self._VN_MIDDLE_NAMES.add("công")
        self._VN_MIDDLE_NAMES.add("mộng")
        self._VN_MIDDLE_NAMES.add("lệnh")
        self._VN_MIDDLE_NAMES.add("cẩm")
        self._VN_MIDDLE_NAMES.add("phúc")
        self._VN_MIDDLE_NAMES.add("nhật")
        self._VN_MIDDLE_NAMES.add("ngọc")
        self._VN_MIDDLE_NAMES.add("thời")
        self._VN_MIDDLE_NAMES.add("sơn")
        self._VN_MIDDLE_NAMES.add("thuỳ")
        self._VN_MIDDLE_NAMES.add("văn")
        self._VN_MIDDLE_NAMES.add("vân")
        self._VN_MIDDLE_NAMES.add("qui")
        self._VN_MIDDLE_NAMES.add("hồng")
        self._VN_MIDDLE_NAMES.add("thế")
        self._VN_MIDDLE_NAMES.add("kim")
        self._VN_MIDDLE_NAMES.add("thị")
        self._VN_MIDDLE_NAMES.add("danh")
        self._VN_MIDDLE_NAMES.add("hoài")
        self._VN_MIDDLE_NAMES.add("tiến")
        self._VN_MIDDLE_NAMES.add("tú")
        self._VN_MIDDLE_NAMES.add("bửu")
        self._VN_MIDDLE_NAMES.add("trung")
        self._VN_MIDDLE_NAMES.add("thiện")
        self._VN_MIDDLE_NAMES.add("tuyết")
        self._VN_MIDDLE_NAMES.add("đăng")
        self._VN_MIDDLE_NAMES.add("như")
        self._VN_MIDDLE_NAMES.add("hùng")
        self._VN_MIDDLE_NAMES.add("vô")
        self._VN_MIDDLE_NAMES.add("miên")
        self._VN_MIDDLE_NAMES.add("quý")
        self._VN_MIDDLE_NAMES.add("quang")
        self._VN_MIDDLE_NAMES.add("đức")
        self._VN_MIDDLE_NAMES.add("ưng")
        self._VN_MIDDLE_NAMES.add("tường")
        self._VN_MIDDLE_NAMES.add("kiều")
        self._VN_MIDDLE_NAMES.add("thảo")
        self._VN_MIDDLE_NAMES.add("xuân")
        self._VN_MIDDLE_NAMES.add("viết")
        self._VN_MIDDLE_NAMES.add("vũ")
        self._VN_MIDDLE_NAMES.add("kế")
        self._VN_MIDDLE_NAMES.add("gia")
        self._VN_MIDDLE_NAMES.add("phước")
        self._VN_MIDDLE_NAMES.add("linh")
        self._VN_MIDDLE_NAMES.add("cao")
        self._VN_MIDDLE_NAMES.add("lệ")
    
        self._VN_FAMILY_NAMES={"bảo"}
        self._VN_FAMILY_NAMES.add("phan")
        self._VN_FAMILY_NAMES.add("lý")
        self._VN_FAMILY_NAMES.add("bao")
        self._VN_FAMILY_NAMES.add("huyền")
        self._VN_FAMILY_NAMES.add("lưu")
        self._VN_FAMILY_NAMES.add("nguyên")
        self._VN_FAMILY_NAMES.add("diêu")
        self._VN_FAMILY_NAMES.add("vĩnh")
        self._VN_FAMILY_NAMES.add("ngô")
        self._VN_FAMILY_NAMES.add("công")
        self._VN_FAMILY_NAMES.add("giang")
        self._VN_FAMILY_NAMES.add("đào")
        self._VN_FAMILY_NAMES.add("bùi")
        self._VN_FAMILY_NAMES.add("hông")
        self._VN_FAMILY_NAMES.add("ngọc")
        self._VN_FAMILY_NAMES.add("chi")
        self._VN_FAMILY_NAMES.add("bưu")
        self._VN_FAMILY_NAMES.add("tạ")
        self._VN_FAMILY_NAMES.add("nguyễn")
        self._VN_FAMILY_NAMES.add("văn")
        self._VN_FAMILY_NAMES.add("qui")
        self._VN_FAMILY_NAMES.add("hồng")
        self._VN_FAMILY_NAMES.add("quy")
        self._VN_FAMILY_NAMES.add("từ")
        self._VN_FAMILY_NAMES.add("trân")
        self._VN_FAMILY_NAMES.add("hường")
        self._VN_FAMILY_NAMES.add("tô")
        self._VN_FAMILY_NAMES.add("mạc")
        self._VN_FAMILY_NAMES.add("bửu")
        self._VN_FAMILY_NAMES.add("đặng")
        self._VN_FAMILY_NAMES.add("huyên")
        self._VN_FAMILY_NAMES.add("lâm")
        self._VN_FAMILY_NAMES.add("võ")
        self._VN_FAMILY_NAMES.add("đinh")
        self._VN_FAMILY_NAMES.add("miên")
        self._VN_FAMILY_NAMES.add("mai")
        self._VN_FAMILY_NAMES.add("hương")
        self._VN_FAMILY_NAMES.add("lương")
        self._VN_FAMILY_NAMES.add("hồ")
        self._VN_FAMILY_NAMES.add("tôn")
        self._VN_FAMILY_NAMES.add("ưng")
        self._VN_FAMILY_NAMES.add("la")
        self._VN_FAMILY_NAMES.add("thân")
        self._VN_FAMILY_NAMES.add("hà")
        self._VN_FAMILY_NAMES.add("dương")
        self._VN_FAMILY_NAMES.add("trịnh")
        self._VN_FAMILY_NAMES.add("tằng")
        self._VN_FAMILY_NAMES.add("lan")
        self._VN_FAMILY_NAMES.add("doãn")
        self._VN_FAMILY_NAMES.add("vinh")
        self._VN_FAMILY_NAMES.add("trần")
        self._VN_FAMILY_NAMES.add("huỳnh")
        self._VN_FAMILY_NAMES.add("vương")
        self._VN_FAMILY_NAMES.add("vũ")
        self._VN_FAMILY_NAMES.add("cao")
        self._VN_FAMILY_NAMES.add("phạm")
        self._VN_FAMILY_NAMES.add("hoàng")
        self._VN_FAMILY_NAMES.add("đỗ")
        self._VN_FAMILY_NAMES.add("trương")
        self._VN_FAMILY_NAMES.add("đoàn")
        self._VN_FAMILY_NAMES.add("diệp")
        self._VN_FAMILY_NAMES.add("lê")
    @property
    def VN_DICT(self):
        return self._VN_DICT
    @property
    def COUNTRY_L_NAME(self):
        return self._COUNTRY_L_NAME
    @COUNTRY_L_NAME.setter
    def COUNTRY_L_NAME(self,value):
        self._COUNTRY_L_NAME.add(value)
    @property
    def COUNTRY_S_NAME(self):
        return self._COUNTRY_S_NAME
    @COUNTRY_S_NAME.setter
    def COUNTRY_S_NAME(self,value):
        self._COUNTRY_S_NAME.add(value)
    @property
    def VN_LOCATIONS(self):
        return self._VN_LOCATIONS
    @VN_LOCATIONS.setter
    def VN_LOCATIONS(self,value):
        self._VN_LOCATIONS.add(value)
    @property
    def WORLD_COMPANY(self):
        return self._WORLD_COMPANY
    @WORLD_COMPANY.setter
    def WORLD_COMPANY(self,value):
        self._WORLD_COMPANY.add(value)
    @property
    def VN_FIRST_SENT_WORDS(self):
        return self._VN_FIRST_SENT_WORDS
    @VN_FIRST_SENT_WORDS.setter
    def VN_FIRST_SENT_WORDS(self,value):
        self._VN_FIRST_SENT_WORDS.add(value)
    @property
    def VN_MIDDLE_NAMES(self):
        return self._VN_MIDDLE_NAMES
    @VN_MIDDLE_NAMES.setter
    def VN_MIDDLE_NAMES(self,value):
        self._VN_MIDDLE_NAMES.add(value)
    @property
    def VN_FAMILY_NAMES(self):
        return self._VN_FAMILY_NAMES
    @VN_FAMILY_NAMES.setter
    def VN_FAMILY_NAMES(self,value):
        self._VN_FAMILY_NAMES.add(value)